### ISSUE TITLE
`YError: Invalid second argument` When starting atsm 1.0.2

### ISSUE THREAD

**Issue by musab** [Feiyang1/awesome-typed-sass-modules#3]
I see the following when running `atsm`: 

```
YError: Invalid first argument. Expected boolean or string but received function.
    at argumentTypeError (.../node_modules/yargs/lib/argsert.js:65:9)
    at parsed.optional.forEach (.../node_modules/yargs/lib/argsert.js:47:39)
    at Array.forEach (<anonymous>)
    at argsert (.../node_modules/yargs/lib/argsert.js:42:21)
    at Object.version (.../node_modules/yargs/yargs.js:757:5)
    at Object.<anonymous> (.../node_modules/awesome-typed-sass-modules/lib/cli.js:36:660)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
```

**Comment by Feiyang1** [comment]
@apollomusa Can you please post the full command, so I can reproduce the issue?

**Comment by apollomusa** [comment]
@Feiyang1 Apologies, the full command: 

`node_modules/.bin/atsm -p 'src/**/*.scss'`

**Comment by apollomusa** [comment]
Any updates?

**Comment by Feiyang1** [comment]
I couldn't reproduce the issue. Did it work before and stopped working on 1.0.2? Did it fail only for this specific command, or it didn't work for you at all?

**Comment by Feiyang1** [comment]
closing due to inactivity.
